# Generated by Django 2.2.2 on 2019-07-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Buyer', models.CharField(max_length=100)),
                ('Seller', models.CharField(max_length=100)),
            ],
        ),
    ]
