# Generated by Django 2.2.2 on 2019-07-08 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bchain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='unconfirmeddata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bchain.Data')),
            ],
        ),
    ]
