# Generated by Django 2.2.2 on 2019-07-11 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bchain', '0002_unconfirmeddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('buyer', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
                ('prev_hash', models.CharField(default='00', max_length=1000)),
                ('hash', models.CharField(default='0', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bchain.Block')),
            ],
        ),
        migrations.RemoveField(
            model_name='unconfirmeddata',
            name='data',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='unconfirmeddata',
        ),
    ]
