# Generated by Django 2.2.2 on 2019-07-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bchain', '0003_auto_20190711_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchain',
            name='id',
        ),
        migrations.AddField(
            model_name='blockchain',
            name='index',
            field=models.IntegerField(default=0, max_length=10000, primary_key=True, serialize=False),
        ),
    ]
