# Generated by Django 2.2.2 on 2019-07-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bchain', '0004_auto_20190711_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockchain',
            old_name='index',
            new_name='id',
        ),
    ]
