# Generated by Django 2.2.2 on 2019-07-11 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bchain', '0005_auto_20190711_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='BChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bchain.Block')),
            ],
        ),
    ]
