# Generated by Django 2.2.2 on 2019-07-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bchain', '0006_bchain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BChain',
        ),
    ]
