# Generated by Django 2.2.2 on 2019-07-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bchain', '0007_delete_bchain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='hash',
            field=models.CharField(default='0', editable=False, max_length=1000),
        ),
    ]
