# Generated by Django 2.2.2 on 2019-07-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bchain', '0009_auto_20190711_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='amount',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='block',
            name='buyer',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='block',
            name='location',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='block',
            name='seller',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
