# Generated by Django 2.2.2 on 2019-07-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bchain', '0010_auto_20190715_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchain',
            name='block',
        ),
        migrations.AddField(
            model_name='blockchain',
            name='amount',
            field=models.CharField(default=None, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='buyer',
            field=models.CharField(default=None, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='hash',
            field=models.CharField(default='0', editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='location',
            field=models.CharField(default=None, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='prev_hash',
            field=models.CharField(default='00', editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='seller',
            field=models.CharField(default=None, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
