# Generated by Django 2.2.2 on 2019-07-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bchain', '0011_auto_20190716_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
